### ISSUE TITLE
Define data structure for content

### ISSUE THREAD

**Issue by axelekwall** [osqledaren/osqledaren-cms#1]
We need to define the data structure for our project. Should probably be discussed with content owners, i.e. text editors.

See Sanity docs:
https://www.sanity.io/docs/content-modelling

**Comment by EllaSoderberg** [comment]
- [ ] Define what content categories should be defined
- [ ] Define what attributes each category should have
- [ ] Code away!

**Comment by EllaSoderberg** [comment]
Content categories: 
* Authors
* Articles
* Categories

**Comment by EllaSoderberg** [comment]
Author attributes: 
* Name
* Profile picture
* Role? (writer, podcaster, etc.)

**Comment by EllaSoderberg** [comment]
Article attributes:
* Title
* Author
* Date
* Read length
* Text
- Images in text

**Comment by EllaSoderberg** [comment]
Category attributes: 
* Title
* Description?

**Comment by EllaSoderberg** [comment]
Podcast attributes:
* Title
* Date
* Image
* Members (more than one?)
* Description
     * Podcast player??

**Comment by EllaSoderberg** [comment]
Extras:
[ ] Add read length for articles

**Comment by axelekwall** [comment]
Implemented with #5
